import { SquareNumber, Board, Hand, Hands, State } from "./definitions";
export declare const MIN_SQUARE_NUMBER: SquareNumber;
export declare const MAX_SQUARE_NUMBER: SquareNumber;
export declare function getSquareNumbers(): SquareNumber[];
export declare const SQUARE_NUMBERS: SquareNumber[];
export declare function getEmptyBoard(): Board;
export declare const EMPTY_BOARD: (import("./definitions").ColorPiece | null)[];
export declare function getHirateBoard(): Board;
export declare const HIRATE_BOARD: (import("./definitions").ColorPiece | null)[];
export declare function getEmptyHand(): Hand;
export declare const EMPTY_HAND: Hand;
export declare function getEmptyHands(): Hands;
export declare const EMPTY_HANDS: Hands;
export declare function getHirateState(): State;
export declare const HIRATE_STATE: State;
